services:
  api-gateway:
    build: .
    container_name: api-gateway 
    image: api-gateway
    ports:
      - 8080:8080
    networks:
      - microservice-net
  redis:
    container_name: redis-api-gateway-container
    image: redis:8.0
    ports:
      - "6301:6379"
    networks:
      - microservice-net

networks:
  microservice-net:
    external: true