// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_times.sql

package database

import (
	"context"
	"database/sql"
)

const createEventTime = `-- name: CreateEventTime :execresult
insert into
    event_times (
        id,
        start_time,
        end_time,
        description,
        creator_id,
        modifier_id,
        event_id,
        deletor_id,
        created_at,
        modified_at,
        deleted_at
    )
values
    (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEventTimeParams struct {
	ID          string
	StartTime   int64
	EndTime     int64
	Description sql.NullString
	CreatorID   string
	ModifierID  string
	EventID     string
	DeletorID   string
	CreatedAt   int64
	ModifiedAt  int64
	DeletedAt   int64
}

func (q *Queries) CreateEventTime(ctx context.Context, arg CreateEventTimeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEventTime,
		arg.ID,
		arg.StartTime,
		arg.EndTime,
		arg.Description,
		arg.CreatorID,
		arg.ModifierID,
		arg.EventID,
		arg.DeletorID,
		arg.CreatedAt,
		arg.ModifiedAt,
		arg.DeletedAt,
	)
}

const getEventTimeById = `-- name: GetEventTimeById :one
select
    et.id,
    et.start_time,
    et.end_time,
    et.description,
    et.event_id,
    et.creator_id,
    et.modifier_id,
    et.deletor_id,
    et.created_at,
    et.modified_at,
    et.deleted_at
from
    event_times et
where
    et.id = ?
limit
    1
`

func (q *Queries) GetEventTimeById(ctx context.Context, id string) (EventTime, error) {
	row := q.db.QueryRowContext(ctx, getEventTimeById, id)
	var i EventTime
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.Description,
		&i.EventID,
		&i.CreatorID,
		&i.ModifierID,
		&i.DeletorID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEventTimes = `-- name: GetEventTimes :many
select
    et.id,
    et.start_time,
    et.end_time,
    et.description,
    et.event_id,
    et.creator_id,
    et.modifier_id,
    et.deletor_id,
    et.created_at,
    et.modified_at,
    et.deleted_at
from
    event_times et
limit
    ?
offset
    ?
`

type GetEventTimesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetEventTimes(ctx context.Context, arg GetEventTimesParams) ([]EventTime, error) {
	rows, err := q.db.QueryContext(ctx, getEventTimes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventTime
	for rows.Next() {
		var i EventTime
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.Description,
			&i.EventID,
			&i.CreatorID,
			&i.ModifierID,
			&i.DeletorID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventTimesByEventId = `-- name: GetEventTimesByEventId :many
select
    et.id,
    et.start_time,
    et.end_time,
    et.description,
    et.event_id,
    et.creator_id,
    et.modifier_id,
    et.deletor_id,
    et.created_at,
    et.modified_at,
    et.deleted_at
from
    event_times et
where
     et.deleted_at = 0 and et.event_id = ?
limit
    ?
offset
    ?
`

type GetEventTimesByEventIdParams struct {
	EventID string
	Limit   int32
	Offset  int32
}

func (q *Queries) GetEventTimesByEventId(ctx context.Context, arg GetEventTimesByEventIdParams) ([]EventTime, error) {
	rows, err := q.db.QueryContext(ctx, getEventTimesByEventId, arg.EventID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventTime
	for rows.Next() {
		var i EventTime
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.Description,
			&i.EventID,
			&i.CreatorID,
			&i.ModifierID,
			&i.DeletorID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEventTime = `-- name: SoftDeleteEventTime :execresult
UPDATE event_times
SET
    deleted_at = ?,
    deletor_id = ?
WHERE
    id = ?
`

type SoftDeleteEventTimeParams struct {
	DeletedAt int64
	DeletorID string
	ID        string
}

func (q *Queries) SoftDeleteEventTime(ctx context.Context, arg SoftDeleteEventTimeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, softDeleteEventTime, arg.DeletedAt, arg.DeletorID, arg.ID)
}

const updateEventTimeById = `-- name: UpdateEventTimeById :execresult
UPDATE event_times
SET
    start_time = COALESCE(UNIX_TIMESTAMP (), start_time),
    end_time = COALESCE(?, end_time),
    description = COALESCE(?, description),
    modifier_id = COALESCE(?, modifier_id),
    modified_at = COALESCE(?, modified_at)
WHERE
    id = ?
`

type UpdateEventTimeByIdParams struct {
	EndTime     int64
	Description sql.NullString
	ModifierID  string
	ModifiedAt  int64
	ID          string
}

// update event_times et
// SET start_time = ?,end_time=?,description = ?,modifier_id = ?, modified_at = ?
// where et.id = ?;
func (q *Queries) UpdateEventTimeById(ctx context.Context, arg UpdateEventTimeByIdParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateEventTimeById,
		arg.EndTime,
		arg.Description,
		arg.ModifierID,
		arg.ModifiedAt,
		arg.ID,
	)
}
