// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_categories.sql

package database

import (
	"context"
	"database/sql"
)

const createCategory = `-- name: CreateCategory :execresult
insert into
    event_categories (
        id,
        title,
        description,
        creator_id,
        modifier_id,
        deletor_id,
        created_at,
        modified_at,
        deleted_at
    )
values
    (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCategoryParams struct {
	ID          string
	Title       string
	Description sql.NullString
	CreatorID   string
	ModifierID  string
	DeletorID   string
	CreatedAt   int64
	ModifiedAt  int64
	DeletedAt   int64
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCategory,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.CreatorID,
		arg.ModifierID,
		arg.DeletorID,
		arg.CreatedAt,
		arg.ModifiedAt,
		arg.DeletedAt,
	)
}

const getCategories = `-- name: GetCategories :many
select
    ec.id,
    ec.title,
    ec.description,
    ec.creator_id,
    ec.modifier_id,
    ec.deletor_id,
    ec.created_at,
    ec.modified_at,
    ec.deleted_at
from
    event_categories ec
order by
    created_at DESC
`

func (q *Queries) GetCategories(ctx context.Context) ([]EventCategory, error) {
	rows, err := q.db.QueryContext(ctx, getCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventCategory
	for rows.Next() {
		var i EventCategory
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatorID,
			&i.ModifierID,
			&i.DeletorID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryById = `-- name: GetCategoryById :one
select
    ec.id,
    ec.title,
    ec.description,
    ec.creator_id,
    ec.modifier_id,
    ec.deletor_id,
    ec.created_at,
    ec.modified_at,
    ec.deleted_at
from
    event_categories ec
where
    ec.id = ?
limit
    1
`

func (q *Queries) GetCategoryById(ctx context.Context, id string) (EventCategory, error) {
	row := q.db.QueryRowContext(ctx, getCategoryById, id)
	var i EventCategory
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatorID,
		&i.ModifierID,
		&i.DeletorID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
	)
	return i, err
}
