// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type TicketsStatus string

const (
	TicketsStatusAvailable TicketsStatus = "available"
	TicketsStatusSoldOut   TicketsStatus = "sold_out"
	TicketsStatusInactive  TicketsStatus = "inactive"
)

func (e *TicketsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketsStatus(s)
	case string:
		*e = TicketsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketsStatus: %T", src)
	}
	return nil
}

type NullTicketsStatus struct {
	TicketsStatus TicketsStatus
	Valid         bool // Valid is true if TicketsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TicketsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketsStatus), nil
}

// Main table of events
type Event struct {
	// event primary key
	ID string
	// event title
	Title string
	// event address
	Address string
	// organizer of event
	OrganizerID string
	// Below to what category is
	EventCategoryID string
	// id of who created this record
	CreatorID string
	// id of who last modified this record
	ModifierID string
	// id of who deleted this record
	DeletorID string
	// create date of row
	CreatedAt int64
	// modify date of row
	ModifiedAt int64
	// delete date of row
	DeletedAt int64
}

// Table category of event
type EventCategory struct {
	// identify the event category
	ID string
	// title of event category
	Title string
	// description of event category
	Description sql.NullString
	// id of who created this record
	CreatorID string
	// id of who last modified this record
	ModifierID string
	// id of who deleted this record
	DeletorID string
	// create date of row
	CreatedAt int64
	// modify date of row
	ModifiedAt int64
	// delete date of row
	DeletedAt int64
}

// Table storing start and end times of events
type EventTime struct {
	// primary key
	ID string
	// start timestamp of the event
	StartTime int64
	// end timestamp of the event
	EndTime int64
	// description of the event time
	Description sql.NullString
	// related event id
	EventID string
	// id of who created this record
	CreatorID string
	// id of who last modified this record
	ModifierID string
	// id of who deleted this record
	DeletorID string
	// create date of row
	CreatedAt int64
	// modify date of row
	ModifiedAt int64
	// delete date of row
	DeletedAt int64
}

// Tickets for events
type Ticket struct {
	// ticket primary key
	ID string
	// ticket title
	Title string
	// ticket price
	Price float64
	// ticket status
	Status TicketsStatus
	// total number of tickets
	TotalQuantity int32
	// number of tickets sold
	SoldQuantity int32
	// relate to event time table
	EventTimeID string
	// id of who created this record
	CreatorID string
	// id of who last modified this record
	ModifierID string
	// id of who deleted this record
	DeletorID string
	// create date of row
	CreatedAt int64
	// modify date of row
	ModifiedAt int64
	// delete date of row
	DeletedAt int64
}
