// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tickets.sql

package database

import (
	"context"
	"database/sql"
)

const createTicket = `-- name: CreateTicket :execresult
insert into
	tickets (
		id,
		title,
		price,
		status,
		total_quantity,
		sold_quantity,
		event_time_id,
		creator_id,
		modifier_id,
		deletor_id,
		created_at,
		modified_at,
		deleted_at
	)
values
	(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTicketParams struct {
	ID            string
	Title         string
	Price         float64
	Status        TicketsStatus
	TotalQuantity int32
	SoldQuantity  int32
	EventTimeID   string
	CreatorID     string
	ModifierID    string
	DeletorID     string
	CreatedAt     int64
	ModifiedAt    int64
	DeletedAt     int64
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTicket,
		arg.ID,
		arg.Title,
		arg.Price,
		arg.Status,
		arg.TotalQuantity,
		arg.SoldQuantity,
		arg.EventTimeID,
		arg.CreatorID,
		arg.ModifierID,
		arg.DeletorID,
		arg.CreatedAt,
		arg.ModifiedAt,
		arg.DeletedAt,
	)
}

const getTickets = `-- name: GetTickets :many
select
	t.id,
	t.title,
	t.price,
	t.status,
	t.total_quantity,
	t.sold_quantity,
	t.creator_id,
	t.modifier_id,
	t.deletor_id,
	t.created_at,
	t.modified_at,
	t.deleted_at,
	t.event_time_id
from
	tickets t
limit
	?
offset
	?
`

type GetTicketsParams struct {
	Limit  int32
	Offset int32
}

type GetTicketsRow struct {
	ID            string
	Title         string
	Price         float64
	Status        TicketsStatus
	TotalQuantity int32
	SoldQuantity  int32
	CreatorID     string
	ModifierID    string
	DeletorID     string
	CreatedAt     int64
	ModifiedAt    int64
	DeletedAt     int64
	EventTimeID   string
}

func (q *Queries) GetTickets(ctx context.Context, arg GetTicketsParams) ([]GetTicketsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTickets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTicketsRow
	for rows.Next() {
		var i GetTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Price,
			&i.Status,
			&i.TotalQuantity,
			&i.SoldQuantity,
			&i.CreatorID,
			&i.ModifierID,
			&i.DeletorID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DeletedAt,
			&i.EventTimeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketsByEventTime = `-- name: GetTicketsByEventTime :many
select
	t.id,
	t.title,
	t.price,
	t.status,
	t.total_quantity,
	t.sold_quantity,
	t.creator_id,
	t.modifier_id,
	t.deletor_id,
	t.created_at,
	t.modified_at,
	t.deleted_at,
	t.event_time_id
from
	tickets t
where
	t.event_time_id = ?
`

type GetTicketsByEventTimeRow struct {
	ID            string
	Title         string
	Price         float64
	Status        TicketsStatus
	TotalQuantity int32
	SoldQuantity  int32
	CreatorID     string
	ModifierID    string
	DeletorID     string
	CreatedAt     int64
	ModifiedAt    int64
	DeletedAt     int64
	EventTimeID   string
}

func (q *Queries) GetTicketsByEventTime(ctx context.Context, eventTimeID string) ([]GetTicketsByEventTimeRow, error) {
	rows, err := q.db.QueryContext(ctx, getTicketsByEventTime, eventTimeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTicketsByEventTimeRow
	for rows.Next() {
		var i GetTicketsByEventTimeRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Price,
			&i.Status,
			&i.TotalQuantity,
			&i.SoldQuantity,
			&i.CreatorID,
			&i.ModifierID,
			&i.DeletorID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DeletedAt,
			&i.EventTimeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketsById = `-- name: GetTicketsById :one
select
	t.id,
	t.title,
	t.price,
	t.status,
	t.total_quantity,
	t.sold_quantity,
	t.creator_id,
	t.modifier_id,
	t.deletor_id,
	t.created_at,
	t.modified_at,
	t.deleted_at,
	t.event_time_id
from
	tickets t
where
	t.id = ?
`

type GetTicketsByIdRow struct {
	ID            string
	Title         string
	Price         float64
	Status        TicketsStatus
	TotalQuantity int32
	SoldQuantity  int32
	CreatorID     string
	ModifierID    string
	DeletorID     string
	CreatedAt     int64
	ModifiedAt    int64
	DeletedAt     int64
	EventTimeID   string
}

func (q *Queries) GetTicketsById(ctx context.Context, id string) (GetTicketsByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getTicketsById, id)
	var i GetTicketsByIdRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Price,
		&i.Status,
		&i.TotalQuantity,
		&i.SoldQuantity,
		&i.CreatorID,
		&i.ModifierID,
		&i.DeletorID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
		&i.EventTimeID,
	)
	return i, err
}

const softDeleteTicket = `-- name: SoftDeleteTicket :execresult
UPDATE tickets
SET
	deleted_at = ?,
	deletor_id = ?
WHERE
	id = ?
`

type SoftDeleteTicketParams struct {
	DeletedAt int64
	DeletorID string
	ID        string
}

func (q *Queries) SoftDeleteTicket(ctx context.Context, arg SoftDeleteTicketParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, softDeleteTicket, arg.DeletedAt, arg.DeletorID, arg.ID)
}

const updateTicketAmount = `-- name: UpdateTicketAmount :execresult
update tickets s 
set
	s.total_quantity = ?,
	s.sold_quantity = ?,
	s.status = ?,
	s.modified_at = ?,
	s.modifier_id = ?
where
	s.id = ?
`

type UpdateTicketAmountParams struct {
	TotalQuantity int32
	SoldQuantity  int32
	Status        TicketsStatus
	ModifiedAt    int64
	ModifierID    string
	ID            string
}

func (q *Queries) UpdateTicketAmount(ctx context.Context, arg UpdateTicketAmountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTicketAmount,
		arg.TotalQuantity,
		arg.SoldQuantity,
		arg.Status,
		arg.ModifiedAt,
		arg.ModifierID,
		arg.ID,
	)
}
