server:
  mode: "dev"
  port: 8085
cors:
  url: "*"

mysql:
  host: ""
  port: 3306
  username: "root"
  password: "root"
  dbname: "ticket4u"
  maxIdleConns: 3
  maxOpenConns: 5
  connMaxLifeTime: 10

redis:
  host: "redis-event-ticket-container"
  port: 6379
  password: ""
  database: 0

log:
  logLevel: "debug"
  fileLogName: "./storage/logs/server.log"
  maxSize: 500
  maxBackups: 3
  maxAge: 7
  compress: true
jwt:
  tokenHourLifeSpan: 1
  accessSecret: "myaccessecrettoken2025"
  accessSecretExpiriedTime: "1h"

kafka:
  brokers:
    - ""
  groupId: "order-service-group"
  topics:
    - "order.created"
    - "order.updated"

cloudinary:
  cloudName: "dmsnw2qpd"
  key: "287679419732832"
  secret: "9Q0zxL5P9C7BKFqp53rp6Riy1ko"
  url: "cloudinary://287679419732832:9Q0zxL5P9C7BKFqp53rp6Riy1ko@dmsnw2qpd"
