server:
  port: 8083
  mode: debug

mysql:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: ""
  dbname: "ticket4u_order"
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifeTime: 3600

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  database: 0

kafka:
  brokers: ["127.0.0.1:9092"]
  groupId: "order-service"
  topics:
    orderCreated: "order.created"

jwt:
  tokenHourLifeSpan: 24
  accessSecret: "yoursecretkey"
  accessSecretExpiriedTime: "1h"

log:
  logLevel: "debug"
  fileLogName: "logs/order_service.log"
  maxSize: 100
  maxBackups: 3
  maxAge: 7
  compress: true

app:
  productUrl: "http://localhost:8081"
