services:
  nestjs-auth-user-service:
    build: .
    container_name: nestjs-auth-user-service
    environment:
      NODE_ENV: container
    env_file:
      - .env.container
    ports:
      - 8087:8087
    depends_on:
      - mysql
      - redis
    networks:
      - microservice-net
  mysql:
    image: mysql:8.0
    container_name: user-auth-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket4u
    ports:
      - 3303:3306
    networks:
      - microservice-net
  redis:
    image: redis:8.0
    container_name: users-auth-redis
    ports:
      - 6303:6379
    networks:
      - microservice-net

networks:
  microservice-net:
    external: true
