services:
  go-event-ticket-service-v2:
    build:
      context: ../go-event-ticket-service
      dockerfile: Dockerfile
    container_name: go-event-ticket-service-v2
    ports:
      - "8085:8085"
    environment:
      - MYSQL_HOST=mysql-event-ticket-container-v2
      - REDIS_HOST=redis-event-ticket-container-v2
      - EUREKA_HOSTNAME=host.docker.internal
      - KAFKA_BROKERS_0=host.docker.internal:9092
    depends_on:
      mysql-event-ticket-container-v2:
        condition: service_healthy
      redis-event-ticket-container-v2:
        condition: service_started

  mysql-event-ticket-container-v2:
    image: mysql:8.0
    container_name: mysql-event-ticket-container-v2
    environment:
      - MYSQL_ROOT_PASSWORD=shopdev
      - MYSQL_DATABASE=ticket4u_test
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-event-ticket-container-v2:
    image: redis:alpine
    container_name: redis-event-ticket-container-v2
    ports:
      - "6381:6379"
