services:
  java-order-service-v2:
    build:
      context: ../java-order-service
      dockerfile: Dockerfile
    container_name: java-order-service-v2
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://order-mysql-v2:3306/ticket4u_test
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=shopdev
      - SPRING_DATA_REDIS_HOST=order-redis-v2
      - SPRING_DATA_REDIS_PORT=6379
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://host.docker.internal:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_IP_ADDRESS=host.docker.internal
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=host.docker.internal:9092
    depends_on:
      order-mysql-v2:
        condition: service_healthy
      order-redis-v2:
        condition: service_started

  order-mysql-v2:
    image: mysql:8.0
    container_name: order-mysql-v2
    environment:
      - MYSQL_ROOT_PASSWORD=shopdev
      - MYSQL_DATABASE=ticket4u_test
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  order-redis-v2:
    image: redis:alpine
    container_name: order-redis-v2
    ports:
      - "6379:6379"
