
APP_NAME = java-order-service
APP_PORT = 8086

dev:
	mvn spring-boot:run

docker-build-up:
	docker compose -f docker-compose.yml up -d --build
docker-up:
	docker compose -f docker-compose.yml up -d

docker-down:
	docker-compose -f docker-compose.yml down -v


