app:
    product-url: http://go-event-ticket-service:8085/api/v1/2025
    payment-url: http://payment-service:8088/api/v1/2025

springdoc:
    api-docs:
        path: /order-service/swagger/json
    swagger-ui:
        path: /order-service/swagger/ui
    
server:
    tomcat:
        threads:
            max: 1000
    servlet:
        context-path: /api/v1/2025
    port: 8086

spring:
    data:
        redis:
            host: order-redis
            port: 6379
    application:
        name: order-service
    jackson:
        default-property-inclusion: non_null
    datasource:
        hikari:
            maximum-pool-size: 100
        url: jdbc:mysql://order-mysql:3306/ticket4u
        # url: jdbc:mysql://localhost:3301/ticket4u
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    kafka:
        listener:
            ack-mode: manual
        bootstrap-servers: kafka-kafka-1-1:9092

        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

        consumer:
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            enable-auto-commit: false
    flyway:
        enabled: true
        locations: classpath:db/migration
        baseline-version: 0

login:
    user:
        jwt:
            secret: abcxyz