version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.8
    container_name: elasticsearch
    ports:
      - "9200:9200"
 

  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.8
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
 

